config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'
  # post 'dashboard/test', to: 'users#testing'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create', as: :users
  get '/stats', to: 'user_study_sessions#show'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :study_sessions

  get '/auth/spotify', as: 'spotify_login'
  get '/auth/:provider/callback', to: 'sessions#update'

  resources :users, except: %i[new create]

  get '/dashboard', to: 'users#show'
  get '/about', to: 'about#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/study_session.rb
# frozen_string_literal: true

class StudySession < ApplicationRecord
  validates :topic, presence: true
  validates :paired, inclusion: { in: [true, false] }
  validates :duration, presence: true
  belongs_to :user

  def self.topics
    StudySession.all.map(&:topic).uniq
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :study_sessions, dependent: :destroy

  has_secure_password

  def total_time
    time = study_sessions.sum(:duration)
    minutes_to_hours(time)
  end

  def paired_time
    time = study_sessions.where(paired: true).sum(:duration)
    minutes_to_hours(time)
  end

  def topics
    study_sessions.all.map(&:topic).uniq
  end

  def topic_time(topic)
    time = study_sessions.where(topic: topic).sum(:duration)
    minutes_to_hours(time)
  end

  def paired_topic_time(topic)
    time = study_sessions.where(topic: topic, paired: true).sum(:duration)
    minutes_to_hours(time)
  end

  def global_time
    your_time = study_sessions.sum(:duration) * 100
    global = StudySession.sum(:duration)
    number = your_time / global.to_f
    number.round(2)
  end

  def minutes_to_hours(minutes_params)
    hours = minutes_params / 60
    minutes = minutes_params % 60
    hours_string = hours.to_s.rjust(2, '0')
    minutes_string = minutes.to_s.rjust(2, '0')
    "#{hours_string} hours and #{minutes_string} minutes."
  end
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def four_oh_four
    render file: '/public/404'
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user&.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      flash[:error] = 'Your email or password was incorrect'
      render :new
    end
  end

  def update
    if current_user
      update_current_user(spotify_info)
    elsif @user = User.find_by(uid: :spotify_info['uid'])
      update_user(spotify_info)
    end
    redirect_to dashboard_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
    flash[:success] = 'Logout Successful'
  end

  private

  def spotify_info
    request.env['omniauth.auth']
  end

  def update_current_user(response_info)
    expires = Time.now + 3600
    current_user.update(uid: response_info['uid'],
                spotify_token: response_info['credentials']['token'],
                refresh_token: response_info['credentials']['refresh_token'],
                token_expiration: expires)
  end

  def update_user(response_info)
    expires = Time.now + 3600
    session[:user_id] = @user.id
    @user.update(spotify_token: response_info['credentials']['token'],
                refresh_token: response_info['credentials']['refresh_token'],
                token_expiration: expires)
  end
end

app/controllers/study_sessions_controller.rb
# frozen_string_literal: true

class StudySessionsController < ApplicationController
  before_action :current_user!

  def new
    @studySession = StudySession.new
  end

  def create
    user = User.find(session[:user_id])
    @studySession = user.study_sessions.create(study_session_params)
    if @studySession.save
      redirect_to "/study_sessions/#{@studySession.id}"
    else
      flash[:error] = @studySession.errors.full_messages.to_sentence
      redirect_to '/study_sessions/new'
    end
  end

  def show
    @studySession = StudySession.find(params[:id])
    @quote = SearchResults.new.get_quote
    playlist_handler
  end

  def destroy
    @studySession = StudySession.find(params[:id])
    @studySession.destroy
    redirect_to '/'
  end

  private

  def study_session_params
    paired_param_converter(params)
    params[:duration] = params[:duration].to_i
    params.permit(:topic, :duration, :paired)
  end

  def paired_param_converter(params)
    if params[:paired] == "1"
      params[:paired] = true
    else
      params[:paired] = false
    end
  end

  def playlist_handler
    if current_user.spotify_token.present?
      @playlists = SearchResults.new.get_playlists(current_user.spotify_token)
    end
  end

  def current_user!
    four_oh_four unless current_user
  end
end

app/controllers/user_study_sessions_controller.rb
# frozen_string_literal: true

class UserStudySessionsController < ApplicationController
  before_action :current_user!

  def current_user!
    four_oh_four unless current_user
  end

  def show
    @user = User.find(session[:user_id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
      flash[:error] = user.errors.full_messages.to_sentence
      redirect_to '/register'
    end
  end

  def edit
    current_user!
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def show
    current_user!
    @quote = SearchResults.new.get_quote
    @playlists = playlist_handler
  end

  def destroy
    User.find(params[:id]).destroy
    session[:user_id] = nil
    flash[:success] = 'Account Successfully Deleted'
    redirect_to '/register'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def playlist_handler
    token = current_user.spotify_token
    if current_user.spotify_token.present?
      @playlists = SearchResults.new.get_playlists(token)
    end
  end

  def current_user!
    four_oh_four unless current_user
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    redirect_to dashboard_path if current_user
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/about/index.html.erb
<main class='about-page'>
  <section class="about-section">
    <h1 class='about-title'>About This App</h1>

    <h2>DESCRIPTION</h2>
    <p>
      This Application was a 4-person project utilizing Ruby on Rails and Sinatra.
      It allows the user to set a time blocked session for them to study. Spotify Premium
      users can opt-in with their Spotify account and listen to music as they study.
      They can track statistics about their sessions within the Stats section including information
      like overall time studied and how long they have studied a specific topic.
    </p>

    <h2>TECH STACK:</h2>
    <h3>Ruby on Rails, Sinatra, Spotify Oauth, Github / Github Project Manager, Travis CI</h3>

    <h2>DEVELOPERS</h2>
    <section class="dev-section">
      <article class="devs">
        <%= image_tag("https://ca.slack-edge.com/T029P2S9M-UED1JSA3U-6298f00f851f-512", width: "200px") %>
        <h3>Name: De'Marcus Kirby</h3>
        <p>Hometown: Dallas, TX</p>
        <%= link_to "Github Profile", "https://www.github.com/KirbyDD", class: 'github-btn' %>
      </article>
      <article class="devs">
        <%= image_tag("https://ca.slack-edge.com/T029P2S9M-UM94QV11B-b41a9a01cfb7-512", width: "200px") %>
        <h3>Name:Paul Debevec</h3>
        <p>Hometown: Berthoud, CO</p>
        <%= link_to "Github Profile", "https://github.com/PaulDebevec", class: 'github-btn' %>
      </article>
      <article class="devs">
        <%= image_tag("https://ca.slack-edge.com/T029P2S9M-UQTT2HLUE-f176f4a950f6-512", width: "200px") %>
        <h3>Name: Colin Alexander</h3>
        <p>Hometown: Los Alamos, NM</p>
        <%= link_to "Github Profile", "https://github.com/coloniusrex", class: 'github-btn' %>
      </article>
      <article class="devs">
        <%= image_tag("https://ca.slack-edge.com/T029P2S9M-UQRM2MBS9-15aa149605b2-512", width: "200px") %>
        <h3>Name: Maxwell Baird</h3>
        <p>Hometown: Broomfield, CO</p>
        <%= link_to "Github Profile", "https://github.com/Maxwell-Baird", class: 'github-btn' %>
      </article>
    </section>
  </section>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JamSession</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= image_tag("https://www.whenthereshelpthereshope.com/wp-content/uploads/52265235_l.jpg", class: "welcome-bg") %>
    <nav>
      <div class="links">
        <%= link_to "Home", '/', class: "nav-link" %>
        <% if current_user %>
          <%= link_to "Dashboard", '/dashboard', class: "nav-link" %>
          <%= link_to "Stats", '/stats', class: "nav-link" %>
        <% end %>
        <%= link_to "About", '/about', class: "nav-link" %>
      </div>
      <div>
        <% if current_user %>
          <%= link_to 'Logout','/logout', method: :delete, class: 'nav-link' %>
        <% end %>
      </div>
    </nav>
    <%= image_tag("https://www.whenthereshelpthereshope.com/wp-content/uploads/52265235_l.jpg", class: "welcome-bg") %>
    <% flash.each do |name, msg| %>
      <div class= "<%=name%>-flash">
        <p><%= msg %></p>
      </div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/study_sessions/new.html.erb
<main class="welcome-page">
  <section class='welcome-content'>
    <div class="sessions-create">
        <h4>Create new study session</h4>
        <section>
          <%= form_with(url: "/study_sessions", method: "post") do %>
          <label for="topic">Topic: </label>
          <p></p>
          <input list="topics" id="topic" name="topic" />
          <p></p>
          <%= label_tag(:duration, "Duration in Minutes:") %>
          <p></p>
          <%= number_field_tag 'duration', nil, min: 1 %>
          <p></p>
          <%= check_box_tag(:paired) %>
          <%= label_tag(:paired, "Paired") %>
          <p></p>
          <%= submit_tag("Create Session") %>
          <% end %>
        </section>
    </div>
    <datalist id="topics">
      <% StudySession.topics.each do |topic| %>
        <option value="<%=topic %>">
      <% end %>
    </datalist>
  </section>
</main>

app/views/study_sessions/show.html.erb
<main class="user-page">
  <div class="row">
    <div class="column-left">
      <section class='user-content'>
          <h3>Quote of the Day from <%= @quote.author %>: </h3>
          <p> <%= @quote.text %></p>
        </section>
      </div>

    <div class="column-center">
  <section class='user-content'>
    <h1> Topic: <%= @studySession.topic %> </h1>
    <h2 id="counter"></h2>
    <% if @studySession.paired == true %>
      <p> You are currently paired </p>
    <% else %>
      <p> You are going solo </p>
    <% end %>
      <%= link_to 'End Session',  @studySession,  method: :delete,
      data: {confirm: "Ending the session early will not allow it to count towards your statistics.\nAre you sure?" } %>
    </section>
  </div>

<div class ="column-right">

  <% if current_user && !current_user.spotify_token.nil?%>
    <div class="dropdown">
    <button class="dropbtn">Select Playlist</button>
      <div class="dropdown-content">  <% @playlists.each do |playlist| %>
          <a href="<%= playlist.url %>" target="search_iframe"><%= playlist.name %></a>
        <% end %>
        <a href="https://open.spotify.com/embed/playlist/2qo6t4Qxc8F4fmr7cHpV8W" target="search_iframe">Default</a>
      </div>
    </div>
  <% end %>
  <iframe src="https://open.spotify.com/embed/playlist/2qo6t4Qxc8F4fmr7cHpV8W" name="search_iframe" width=100% height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>

  </div>
  </div>
</main>
<script type="text/javascript">
  countdown(<%= @studySession.duration %>);
</script>

app/views/user_study_sessions/show.html.erb
<main class="stats-page">
  <section class='stats-content'>
    <div class="row">
      <div class="column">
        <h3> Total time spent studying:</h3>
          <p><%= @user.total_time %></p>
          <p>--------------------------------</p>

        <h3> Paired time spent studying:</h3>
          <p><%= @user.paired_time %></p>
          <p>--------------------------------</p>
        <h2> Web Statistics: </h2>
          <p> You make up <%= @user.global_time %>% of the study time on the website</p>
          <p>--------------------------------</p>
      </div>
      <div class="column">
        <h2> Individual Topics: </h2>
        <% @user.topics.each do |topic| %>
        <h4> <%= topic %> </h4>
        <p>Time spent studying: <%= @user.topic_time(topic)%></p>
        <p>Studying while paired: <%= @user.paired_topic_time(topic)%></p>
        <p>--------------------------------</p>
        <% end %>
      </div>
  </div>
  </section>
</main>

app/views/users/edit.html.erb
<main class="user-page">
  <section class='user-content'>
    <%= form_with model: @user do %>
      <%= label_tag :name %>
      <%= text_field(:user, :name) %>
      <p></p>
      <%= label_tag :email %>
      <%= text_field(:user, :email) %>
      <p></p>
      <%= submit_tag 'Update' %>
    <% end %>
  </section>
</main>

app/views/users/new.html.erb
<main class="user-page">
  <section class='user-content'>
    <%= form_with model: @user do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <p></p>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <p></p>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <p></p>
      <%= f.submit 'Register' %>
    <% end %>
  </section>
</main>

app/views/users/show.html.erb
<main class="user-page">
  <div class="row">
    <div class="column-left">
      <section class='user-content'>
          <h3>Quote of the Day from <%= @quote.author %>: </h3>
          <p> <%= @quote.text %></p>
        </section>
      </div>
    <div class="column-center">
      <section class='user-content'>
    <h2>Welcome <%= current_user.name %></h2>

    <p>E-Mail: <%= current_user.email %></p>

<%= link_to 'New Study Session', '/study_sessions/new', method: :get %>
<p><%= link_to 'Edit Profile', edit_user_path(current_user) %></p>
<p><%= link_to 'Delete Profile', "/users/#{current_user.id}", method: :delete %></p>
<% if current_user && current_user.spotify_token.nil? %>
  <%= button_to "Connect to Spotify", spotify_login_path, class: "welcome-btn", method: :get %>
<% end %>

    <% if current_user.study_sessions.present? %>
      <p>Previous Sessions</p>
      <% current_user.study_sessions.limit(3).each do |session| %>
        <p>Topic: <%= session.topic %> //
        <%= session.duration %> mins</p>
        <%= button_to 'Repeat Session', "/study_sessions", method: :post, params:{id:session.id, topic:session.topic, duration:session.duration} %>
      <% end %>
    <% end %>
  </section>
</div>
  <div class ="column-right">
    <% if current_user && !current_user.spotify_token.nil?%>
      <div class="dropdown">
      <button class="dropbtn">Select Playlist</button>
        <div class="dropdown-content" role="menu">  <% @playlists.each do |playlist| %>
            <a href="<%= playlist.url %>" target="search_iframe"><%= playlist.name %></a>
          <% end %>
          <a href="https://open.spotify.com/embed/playlist/2qo6t4Qxc8F4fmr7cHpV8W" target="search_iframe">Default</a>
        </div>
      </div>
    <% end %>
    <iframe src="https://open.spotify.com/embed/playlist/2qo6t4Qxc8F4fmr7cHpV8W" name="search_iframe" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
    </div>
  </div>
</main>

app/views/welcome/index.html.erb
<main class="welcome-page">
  <section class='welcome-content'>
    <h1 class="welcome-title">Welcome to Jam Session.</h1>
    <p>This app provides you the ability to time block your study session while
      also being able to listen to music from Spotify.
    </p>
    <h3>Please Register or Log In.</h3>
    <div class="welcome-btns">
      <%= button_to "Register", "/register", class: "welcome-btn", method: :get %>
      <%= button_to "Login", "/login", class: "welcome-btn", method: :get %>
    </div>
  </section>
</main>